name: Lint binary, Build Docker image, and publish the image
on:
  push:
    paths-ignore:
      - "LICENSE"
      - "README.md"
      - "renovate.json"
      - ".github/workflows/**"
      - "!.github/workflows/build-and-publish.yml"
  pull_request:
    paths-ignore:
      - "LICENSE"
      - "README.md"
      - "renovate.json"
      - ".github/workflows/**"
      - "!.github/workflows/build-and-publish.yml"

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: canary
      - name: Run fmt
        run: deno fmt --check
      - name: Run lint
        run: deno lint
      - name: Run tests
        run: deno test -A

  build-image:
    name: Build Docker image, and Publish on main branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/mecab-server
          tags: |
            type=sha,prefix=sha-,suffix=,format=short
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=raw,value=latest
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
